baseURL = "https://pixfri.github.io"
title = "Jean Letessier"
theme = "typo"
paginate = 5
languageCode = "fr-fr"
DefaultContentLanguage = "fr"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

disableKinds = ['taxonomy']

[params]

favicon = "favicon.ico"

  math = true

  homeIntro = true
  homeIntroTitle = "Bonjour !"
  homeIntroContent = """
  Je me nomme Jean Letessier. Je suis un développeur interessé par le modding, le jeu vidéo et le rendu graphique.
  J'utilise principalement le Java et le C++, quelques fois ce dernier accompagné de Vulkan pour faire du rendu graphique.
  """

  homeCollectionTitle = "Posts"
  homeCollection = 'posts'

  paginationSize = 100

  [[params.social]]
    name = "GitHub"
    url = "https://github.com/Pixfri"

  [[params.social]]
    name = "YouTube"
    url = "https://youtube.com/@pixfri"

  [[params.menu]]
    name = "Page d'accueil"
    url = "/"

  [[params.menu]]
    name = "Articles"
    url = "/posts"

  [[params.menu]]
    name = "Plan du Site"
    url = "/plan_du_site"

  [[params.menu]]
    name = "Curriculum vitae"
    url = "/cv"

[markup]
  [markup.highlight]
    style = "algol"