baseURL = "https://pixfri.github.io"
title = "Jean Letessier"
theme = "typo"
paginate = 5
languageCode = "fr-fr"
DefaultContentLanguage = "fr"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

disableKinds = ['taxonomy']

[params]

favicon = "favicon.ico"

  math = true

  homeIntro = true
  homeIntroTitle = "Bonjour !"
  homeIntroContent = """
  Je m'appelle Jean LETESSIER, et je fais de la programmation graphique et du développement de moteur de jeu en C++. 
  """

  homeCollectionTitle = "Posts"
  homeCollection = 'posts'

  paginationSize = 100

  [[params.social]]
    name = "GitHub"
    url = "https://github.com/Pixfri"

  [[params.social]]
    name = "YouTube"
    url = "https://youtube.com/@pixfri"

  [[params.menu]]
    name = "Page d'accueil"
    url = "/"

  [[params.menu]]
    name = "Articles"
    url = "/posts"

  [[params.menu]]
    name = "Plan du Site"
    url = "/plan_du_site"

  [[params.menu]]
    name = "Curriculum vitae"
    url = "/cv"

  [[params.menu]]
    name = "Présentation"
    url = "/posts/presentation"

[markup]
  [markup.highlight]
    style = "algol"